"""Run the real Local controller with deterministic publication-edge fixtures."""

from __future__ import annotations

import copy
import json
import os
import sys
import threading
import time
from pathlib import Path

from docker.models.containers import Container
from docker.models.images import ImageCollection
from docker.models.networks import Network

sys.path.insert(0, "/app")

from install import bindings
from local import app
from local.install import developers

RESOLUTION_PATH = Path("/var/lib/shimpz-local/publications/test-resolution.json")
FIXTURE_ICON = b"canonical icon"


class _Developers:
    def __init__(self, resolution: dict[str, object]) -> None:
        self._resolution = resolution

    def resolve(self, source_digest: str) -> dict[str, object]:
        if source_digest != self._resolution["source_digest"]:
            raise developers.PublicationNotInstallableError("publication is not available")
        return copy.deepcopy(self._resolution)

    def latest(self, source_digest: str) -> dict[str, object]:
        return self.resolve(source_digest)

    def icon(self, source_digest: str, icon_digest: str) -> bytes:
        resolution = self.resolve(source_digest)
        if icon_digest != resolution["icon_digest"]:
            raise developers.DevelopersError("publication icon digest mismatch")
        return FIXTURE_ICON


class _ArtifactTrust:
    def __init__(self, resolution: dict[str, object]) -> None:
        self._resolution = resolution

    def verify(self, resolution: dict[str, object]) -> None:
        if resolution != self._resolution:
            raise RuntimeError("publication trust fixture mismatch")


class _LocalRegistryContract:
    def validate(self, _schema_name: str, _resolution: object) -> None:
        """Admit the loopback registry reference generated by this Docker fixture."""


class _UninstallSpans:
    """Record wall-clock spans only inside a fixture uninstall request."""

    def __init__(self) -> None:
        self.active = threading.Lock()
        self.thread = threading.local()
        self.sequence = 0

    def timed(self, name: str, operation):
        def wrapped(*args, **kwargs):
            state = getattr(self.thread, "state", None)
            if state is None:
                return operation(*args, **kwargs)
            parent = state["stack"][-1] if state["stack"] else None
            state["stack"].append(name)
            started = time.perf_counter_ns()
            try:
                return operation(*args, **kwargs)
            finally:
                elapsed = (time.perf_counter_ns() - started) / 1_000_000
                state["stack"].pop()
                state["spans"].append({"name": name, "parent": parent, "ms": round(elapsed, 3)})

        return wrapped

    def uninstall(self, operation):
        def wrapped(*args, **kwargs):
            if not self.active.acquire(blocking=False):
                raise RuntimeError("overlapping fixture uninstall measurement")
            self.sequence += 1
            state = {"stack": [], "spans": []}
            self.thread.state = state
            started = time.perf_counter_ns()
            try:
                return operation(*args, **kwargs)
            finally:
                elapsed = (time.perf_counter_ns() - started) / 1_000_000
                print(
                    "SHIMPZ-PERF-UNINSTALL "
                    + json.dumps({"seq": self.sequence, "total_ms": round(elapsed, 3), "spans": state["spans"]}),
                    flush=True,
                )
                del self.thread.state
                self.active.release()

        return wrapped


def _install_uninstall_spans() -> None:
    recorder = _UninstallSpans()
    targets = (
        (app.AssistantLifecycle, ("_resolve", "_network", "_assistant_container", "_validate_container_profile")),
        (app.AssistantLifecycle, ("_team_has_egress_assistant", "_release_assistant_egress", "_queue_residue")),
        (app.AssistantLifecycle, ("sweep_residues", "_binding_uses_image", "_remove_retired_image")),
        (app.AssistantLifecycle, ("_delete_retired_image", "_disconnect_egress_proxy")),
        (app.ChatTurnService, ("_delete_chat_continuation", "_delete_assistant_integration_state")),
        (app.ChatTurnService, ("_delete_assistant_stored_input_state",)),
        (Container, ("remove",)),
        (ImageCollection, ("remove",)),
        (Network, ("disconnect",)),
    )
    for owner, names in targets:
        for name in names:
            label = f"{owner.__name__}.{name}" if owner in (Container, ImageCollection, Network) else name
            setattr(owner, name, recorder.timed(label, getattr(owner, name)))
    original = app.AssistantLifecycle.uninstall_assistant
    app.AssistantLifecycle.uninstall_assistant = recorder.uninstall(original)


def main() -> int:
    resolution = json.loads(RESOLUTION_PATH.read_bytes())
    bindings._CONTRACTS = _LocalRegistryContract()
    app.local_developers.DevelopersClient = lambda: _Developers(resolution)
    app.artifact_trust.ArtifactTrustVerifier = lambda *_args, **_kwargs: _ArtifactTrust(resolution)
    if os.environ.get("SHIMPZ_PERF_UNINSTALL_SPANS") == "1":
        _install_uninstall_spans()
    return app.main()


if __name__ == "__main__":
    raise SystemExit(main())
