"""Run the real Local controller with deterministic publication-edge fixtures."""

from __future__ import annotations

import copy
import json
import os
import sys
import threading
import time
from pathlib import Path

from docker.models.containers import Container, ContainerCollection
from docker.models.images import ImageCollection
from docker.models.networks import Network

sys.path.insert(0, "/app")

from assistant import manifest as assistant_manifest
from install import bindings
from local import app
from local.install import developers
from local.install import registry as local_registry

RESOLUTION_PATH = Path("/var/lib/shimpz-local/publications/test-resolution.json")
FIXTURE_ICON = b"canonical icon"


class _Developers:
    def __init__(self, resolution: dict[str, object]) -> None:
        self._resolution = resolution

    def resolve(self, source_digest: str) -> dict[str, object]:
        if source_digest != self._resolution["source_digest"]:
            raise developers.PublicationNotInstallableError("publication is not available")
        return copy.deepcopy(self._resolution)

    def latest(self, source_digest: str) -> dict[str, object]:
        return self.resolve(source_digest)

    def icon(self, source_digest: str, icon_digest: str) -> bytes:
        resolution = self.resolve(source_digest)
        if icon_digest != resolution["icon_digest"]:
            raise developers.DevelopersError("publication icon digest mismatch")
        return FIXTURE_ICON


class _ArtifactTrust:
    def __init__(self, resolution: dict[str, object]) -> None:
        self._resolution = resolution

    def verify(self, resolution: dict[str, object]) -> None:
        if resolution != self._resolution:
            raise RuntimeError("publication trust fixture mismatch")


class _LocalRegistryContract:
    def validate(self, _schema_name: str, _resolution: object) -> None:
        """Admit the loopback registry reference generated by this Docker fixture."""


class _PhaseSpans:
    """Record wall-clock spans only inside fixture lifecycle requests."""

    def __init__(self) -> None:
        self.active = threading.Lock()
        self.thread = threading.local()
        self.sequence: dict[str, int] = {}

    def timed(self, name: str, operation):
        def wrapped(*args, **kwargs):
            state = getattr(self.thread, "state", None)
            if state is None:
                return operation(*args, **kwargs)
            parent = state["stack"][-1] if state["stack"] else None
            state["stack"].append(name)
            started = time.perf_counter_ns()
            try:
                return operation(*args, **kwargs)
            finally:
                elapsed = (time.perf_counter_ns() - started) / 1_000_000
                state["stack"].pop()
                state["spans"].append({"name": name, "parent": parent, "ms": round(elapsed, 3)})

        return wrapped

    def root(self, operation_name: str, operation):
        def wrapped(*args, **kwargs):
            if not self.active.acquire(blocking=False):
                raise RuntimeError("overlapping fixture lifecycle measurement")
            sequence = self.sequence.get(operation_name, 0) + 1
            self.sequence[operation_name] = sequence
            state = {"stack": [], "spans": []}
            self.thread.state = state
            started = time.perf_counter_ns()
            try:
                return operation(*args, **kwargs)
            finally:
                elapsed = (time.perf_counter_ns() - started) / 1_000_000
                print(
                    f"SHIMPZ-PERF-{operation_name} "
                    + json.dumps({"seq": sequence, "total_ms": round(elapsed, 3), "spans": state["spans"]}),
                    flush=True,
                )
                del self.thread.state
                self.active.release()

        return wrapped


def _install_phase_spans() -> None:
    recorder = _PhaseSpans()
    targets = (
        (app.AssistantLifecycle, ("_resolve", "_network", "_assistant_container", "_validate_container_profile")),
        (app.AssistantLifecycle, ("_team_has_egress_assistant", "_release_assistant_egress", "_queue_residue")),
        (app.AssistantLifecycle, ("sweep_residues", "_binding_uses_image", "_remove_retired_image")),
        (app.AssistantLifecycle, ("_delete_retired_image", "_disconnect_egress_proxy")),
        (app.AssistantLifecycle, ("install_assistant", "_trusted_image", "_create_assistant_container")),
        (app.AssistantLifecycle, ("_reserve_assistant_egress_environment", "_admit_assistant_allowed_hosts")),
        (app.AssistantLifecycle, ("_activate_assistant_egress", "_validate_container", "_wait_ready")),
        (app.AssistantLifecycle, ("_active_assistant_genesis",)),
        (app.ChatTurnService, ("_delete_chat_continuation", "_delete_assistant_integration_state")),
        (app.ChatTurnService, ("_delete_assistant_stored_input_state",)),
        (Container, ("remove",)),
        (Container, ("start", "get_archive")),
        (ContainerCollection, ("create",)),
        (ImageCollection, ("remove",)),
        (ImageCollection, ("get", "pull")),
        (Network, ("disconnect", "connect")),
    )
    for owner, names in targets:
        for name in names:
            label = (
                f"{owner.__name__}.{name}"
                if owner in (Container, ContainerCollection, ImageCollection, Network)
                else name
            )
            setattr(owner, name, recorder.timed(label, getattr(owner, name)))
    for name in ("_resolved_publication", "_verify_publication_assets", "_apply_publication"):
        service = app.local_install_service
        setattr(service, name, recorder.timed(name, getattr(service, name)))
    app.AssistantLifecycle.uninstall_assistant = recorder.root("UNINSTALL", app.AssistantLifecycle.uninstall_assistant)
    app.LocalController.install_publication = recorder.root("INSTALL", app.LocalController.install_publication)


def _install_chat_spans() -> None:
    recorder = _PhaseSpans()
    targets = (
        (app.AssistantLifecycle, ("_validate_container", "_egress_proxy", "_admit_assistant_allowed_hosts")),
        (local_registry.AssistantRegistry, ("get",)),
        (assistant_manifest.ManifestContractCache, ("get",)),
        (assistant_manifest.MachineContractCache, ("get",)),
        (ContainerCollection, ("list", "get")),
        (Container, ("get_archive",)),
    )
    for owner, names in targets:
        for name in names:
            setattr(owner, name, recorder.timed(f"{owner.__name__}.{name}", getattr(owner, name)))
    assistant_manifest.reviewed_manifest_contract = recorder.timed(
        "reviewed_manifest_contract", assistant_manifest.reviewed_manifest_contract
    )
    app.ChatTurnService._active_chat_assistants = recorder.root(
        "CHAT-ADMISSION", app.ChatTurnService._active_chat_assistants
    )


def main() -> int:
    resolution = json.loads(RESOLUTION_PATH.read_bytes())
    bindings._CONTRACTS = _LocalRegistryContract()
    app.local_developers.DevelopersClient = lambda: _Developers(resolution)
    app.artifact_trust.ArtifactTrustVerifier = lambda *_args, **_kwargs: _ArtifactTrust(resolution)
    if os.environ.get("SHIMPZ_PERF_PHASE_SPANS") == "1" and os.environ.get("SHIMPZ_PERF_CHAT_SPANS") == "1":
        raise RuntimeError("fixture performance span modes cannot be combined")
    if os.environ.get("SHIMPZ_PERF_PHASE_SPANS") == "1":
        _install_phase_spans()
    if os.environ.get("SHIMPZ_PERF_CHAT_SPANS") == "1":
        _install_chat_spans()
    return app.main()


if __name__ == "__main__":
    raise SystemExit(main())
