"""Run the real Local controller with deterministic publication-edge fixtures."""

from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

sys.path.insert(0, "/app")

from install import bindings
from local import app
from local.install import developers

RESOLUTION_PATH = Path("/var/lib/shimpz-local/publications/test-resolution.json")
FIXTURE_ICON = b"canonical icon"


class _Developers:
    def __init__(self, resolution: dict[str, object]) -> None:
        self._resolution = resolution

    def resolve(self, source_digest: str) -> dict[str, object]:
        if source_digest != self._resolution["source_digest"]:
            raise developers.PublicationNotInstallableError("publication is not available")
        return copy.deepcopy(self._resolution)

    def latest(self, source_digest: str) -> dict[str, object]:
        return self.resolve(source_digest)

    def icon(self, source_digest: str, icon_digest: str) -> bytes:
        resolution = self.resolve(source_digest)
        if icon_digest != resolution["icon_digest"]:
            raise developers.DevelopersError("publication icon digest mismatch")
        return FIXTURE_ICON


class _ArtifactTrust:
    def __init__(self, resolution: dict[str, object]) -> None:
        self._resolution = resolution

    def verify(self, resolution: dict[str, object]) -> None:
        if resolution != self._resolution:
            raise RuntimeError("publication trust fixture mismatch")


class _LocalRegistryContract:
    def validate(self, _schema_name: str, _resolution: object) -> None:
        """Admit the loopback registry reference generated by this Docker fixture."""


def main() -> int:
    resolution = json.loads(RESOLUTION_PATH.read_bytes())
    bindings._CONTRACTS = _LocalRegistryContract()
    app.local_developers.DevelopersClient = lambda: _Developers(resolution)
    app.artifact_trust.ArtifactTrustVerifier = lambda *_args, **_kwargs: _ArtifactTrust(resolution)
    return app.main()


if __name__ == "__main__":
    raise SystemExit(main())
